cache:
  enable: true
minify: true
sidebar:
  position: left
  display: always

social:
  GitHub: https://github.com/zshnb || fab fa-github
social_icons:
  enable: true
site_state: true
language: zh-CN
symbols_count_time:
  separated_meta: false
  item_text_total: true
  item_text_post: true
tag_icon: true
post_navigation: left
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive

footer:
  since: 2019
  beian:
    enable: true
    icp: 浙ICP备2023031828号

index_with_subtitle: true
exturl: true
exturl_icon: true
baidu_site_verification: codeva-KVoPqmDeib
bing_site_verification: FDEF7F052E48D8D1B8136A8B3DF8AF9B

