name: Deploy blog
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: prepare node env
        uses: actions/setup-node@v1
        with:
          node-version: "18.18.0"
      - name: set github profile
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.name 'zshnb' # github用户名
          git config --global user.email 'a857681664@gmail.com' # github邮箱
      - name: hexo generate
        run: |
          npm i -g hexo
          npm i
          hexo clean && hexo g && hexo d
      - name: ssh remove server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd blog
            git pull origin gh-pages --rebase
            sudo nginx -s reload
            
